### ISSUE TITLE
strange values from VESC

### ISSUE THREAD

**Issue by sebbi207** [Peemouse/VescUart#2]
Hi, we are sorry to bother You, we are students from Germany and we have some troubles with your code.
we get the following Output running the  getVescValues example:
![Screenshot (2)](https://user-images.githubusercontent.com/51949756/59673282-4db60180-91c1-11e9-9cdd-e5b2682af966.png)

We added UART.setDebugPort(&Serial); to your code. The VESC is set in PPM&UART mode.

We also tried using a voltage divider but it didn´t change the result.
![Voltage Devider](https://user-images.githubusercontent.com/51949756/59674077-cd909b80-91c2-11e9-94d1-843b03b3106e.png)

Do You have any idea, that could solve our probleme. We would appreciate your help.

**Comment by joseguerr** [comment]
Hey guys,

The cables should be crossed (RX to TX and vice-versa). Also you dont need resistances to connect them. Connect the arduino ground to the VESC ground directly, again no need for resistences. 

If the code does not work, try this one https://github.com/SolidGeek/VescUart

Change baudrate from 19200 to 115200, so that you have something like this on your setup.

  Serial1.begin(115200);
  
  while (!Serial) {;}

  /** Define which ports to use as UART */
  UART.setSerialPort(&Serial1);
  UART.setDebugPort(&Serial);


Make sure the ground is making a good connection!

By the way, if you are using Arduino Uno it won't work, you need more than 1 serial port. For instance Arduino mega. Hope it helps!

**Comment by sebbi207** [comment]
hi thanks for your answer.
we are using arduino mega 2560 so it should work with one of the seriel ports.
the boaudrate is set correctly and tx rx is connected correctly too.
we dumped the resistences from our connection but still the same output.

the vesc is set to ppm&UART.
still no idea what could be wrong :/

**Comment by sebbi207** [comment]
i also tried the code from solid geek but still failed to get data.
then i added  UART.setDebugPort(&Serial); and got this:
![Screenshot (4)](https://user-images.githubusercontent.com/51949756/60086376-40f25a00-973b-11e9-969b-008abd717c20.png)

**Comment by sebbi207** [comment]
we finally got the right values. we tried serial3 instead of serial1. seems like serial 1 isn´t working right on our arduino.
